input {
  http {
    host => "0.0.0.0"
    port => 8080
    codec => json
  }
}

filter {
  if [Timestamp] {
    date {
      match => [ "Timestamp", "ISO8601" ]
      target => "@timestamp"
    }
  }

  mutate {
    add_field => {
      "application" => "PragueMicroclimateProject"
    }
  }
}

output {
  elasticsearch {
    hosts => [ "${ELASTIC_HOSTS}" ]
    user => "${ELASTIC_USER}"
    password => "${ELASTIC_PASSWORD}"
    index => "prague-microclimate-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
